#!/usr/bin/env bash
# display information about subdomains.

dom_info() {
	DOM=$1
	SUB=$2
	RECORD=$(dig "$SUB.$DOM" +noall +answer | awk '{ print $4 }')
	IP=$(dig "$SUB.$DOM" +noall +answer | awk '{ print $NF }')
	echo "The subdomain $SUB is a $RECORD record and points to $IP"
}

if [ "$#" -eq 1 ]
then
	dom_info "$1" "www"
	dom_info "$1" "lb-01"
	dom_info "$1" "web-01"
	dom_info "$1" "web-02"
elif [ "$#" -eq 2 ]
then
	dom_info "$1" "$2"
fi