#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt -y update
sudo apt -y install nginx
echo 'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
