#!/usr/bin/env bash
# Install and configure HAproxy

apt -y update
apt -y install haproxy

echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 2835-web-01 18.234.233.93:80 check
        server 2835-web-02 35.243.205.77:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
