#!/usr/bin/env bash
# fix Nginx server to listen on 80 (symbolic link prob)

rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
