#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=1
while (( i <= 8 ))
do
    if (( i == 4 ))
    then
        echo "bad luck"
    elif (( i == 7 ))
    then
        echo "good luck"
    fi
    echo "Holberton School"
    (( i++ ))
done
