#!/usr/bin/env bash
# Install firewall ufw and configure to deny all
# exepte ssh/22 http/80 and https/443

sudo apt install -y ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
